### ISSUE TITLE
Error: `403: Resource not accessible by integration`

### ISSUE THREAD

**Issue by elsuizo** [taiki-e/upload-rust-binary-action#15]
Hi i want to use this to pack a substrate node but i got: 

```bash
HTTP 403: Resource not accessible by integration
```

Any idea what could be wrong?

this is my `yml` configuration file:

https://github.com/elsuizo/substrate-node-packaging-test/blob/main/.github/workflows/release-binary.yml

Thanks in advance

**Comment by taiki-e** [comment]
One possibility is that write permission of GITHUB_TOKEN is missing.

Adding the following two lines to the workflow or changing the default permissions for the repository to "read and write permissions" (see the second section of [this post](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)) may fix the problem.


```yml
permissions:
  contents: write
```

**Comment by elsuizo** [comment]
Solved, Thanks for your time!!!

**Comment by ThreeDeeJay** [comment]
@taiki-e Any idea why I setting [`permissions: contents: write`](https://github.com/ThreeDeeJay/dsoal/actions/runs/10519845953/workflow#L4) still [fails here](https://github.com/ThreeDeeJay/dsoal/actions/runs/10519845953/job/29147871398#step:8:29)? 
The [same happens](https://github.com/ThreeDeeJay/dsoal/actions/runs/10519799619/job/29147757216#step:8:29) when setting [`permissions: write-all`](https://github.com/ThreeDeeJay/dsoal/actions/runs/10519799619/workflow#L3).

Oddly enough, after [removing  `--target COMMITHASH`](https://github.com/ThreeDeeJay/dsoal/commit/6be02ee856e64bad58b081be16a65d72348e9f6d) it [works](https://github.com/ThreeDeeJay/dsoal/actions/runs/10519927172/job/29148080703#step:8:29) but I'm trying to create retroactive releases linked to their respective commit, so I really need to pass that argument, and I even tried setting that branch as default so I'm not sure what I'm missing.

```
 --target <branch> 
    Target branch or full commit SHA (default [main branch])
```
I was able to run the exact same commands while logged in on my PC and it worked, so I suspect this may be a limitation of the GitHub Actions token permissions, but then again, it's already set to read+write in the workflow *and* in the repo's Settings > Actions > General > Workflow permissions 🤔
