### ISSUE TITLE
include directory to archive

### ISSUE THREAD

**Issue by Hulxv** [taiki-e/upload-rust-binary-action#25]
is it possible to include a directory in the archive by 'include' property?

**Comment by taiki-e** [comment]
I hadn't tested it yet, but we use `-r` flag on `cp`, so it should work.

https://github.com/taiki-e/upload-rust-binary-action/blob/2ef6065015f8372403d76e6a1fb2f8094c5d6f18/main.sh#L206

**Comment by Hulxv** [comment]
Ok, thanks for your response.
I will try that
