### ISSUE TITLE
Action fails if Github CLI not installed

### ISSUE THREAD

**Issue by andrewthetechie** [taiki-e/upload-rust-binary-action#26]
```
/opt/gha-runner/_work/_actions/taiki-e/upload-rust-binary-action/v1/main.sh: line 264: gh: command not found
Error: Command failed: bash --noprofile --norc /opt/gha-runner/_work/_actions/taiki-e/upload-rust-binary-action/v1/main.sh
```

Found this when running on my self-hosted runners on ubuntu-20.04.

**Comment by taiki-e** [comment]
Thanks for the report. I've added a compatibility note to readme: https://github.com/taiki-e/upload-rust-binary-action#compatibility

> This action has been tested for action runners hosted by GitHub.
> To use this action in self-hosted runners or in containers, you will need to install at least the following:
> 
> - rustup, cargo, rustc
> - bash, GNU Coreutils
> - gh (GitHub CLI)
> - tar, zip (only Unix-like)
> - 7z (only Windows)
> - brew (only macOS)
