### ISSUE TITLE
Support (or document) fully-static builds with 'musl'

### ISSUE THREAD

**Issue by chshersh** [taiki-e/upload-rust-binary-action#29]
First of all, thanks a lot for working on this GitHub Action! 🙏🏻 
It's amazing how smoothly it works 🤯 I was able to configure binary releases with GitHub Actions in a matter of minutes and everything worked even better than I expected.

When creating [a release of my tool](https://github.com/chshersh/tool-sync/releases/tag/v0.1.0), I've noticed that the asset has name `tool-x86_64-unknown-linux-gnu.tar.gz` and that the binary is actually dynamically linked:

```shell
$ ldd tool 
	linux-vdso.so.1 (0x00007fff1e19e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f89aa7ac000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f89aa7a7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f89aa6c0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f89aa6bb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f89aa493000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f89aaaee000)
```

Is there a way to create statically linked binaries with musl?

Here is my release workflow:

* https://github.com/chshersh/tool-sync/blob/main/.github/workflows/release.yml

<hr>

I've noticed an example usage of `musl` in the following repository:

* https://github.com/taiki-e/cargo-hack/blob/202e6e59d491c9202ce148c9ef423853267226db/.github/workflows/release.yml#L59-L60

```yaml
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
```

But I'm not quite sure how it works 🤔 Could you explain how can I use this workflow to link my binary statically?

Thanks a lot! 🙏🏻

**Comment by taiki-e** [comment]
`*-unknown-linux-musl` except for mips uses static-linking by default, so (basically) you only need to specify the `*-unknown-linux-musl` target.

See also [cross-compilation example](https://github.com/taiki-e/upload-rust-binary-action#example-workflow-cross-compilation).

**Comment by chshersh** [comment]
@taiki-e Thanks a lot for the quick response! This is exactly what I was looking for 💝
