### ISSUE TITLE
sha256sum not found on macOS runners

### ISSUE THREAD

**Issue by chshersh** [taiki-e/upload-rust-binary-action#30]
When using the `checksum` field of this action with the `sha256` field, I see the following error on macOS runners:

```
/Users/runner/work/_actions/taiki-e/upload-rust-binary-action/v1/main.sh: line 277: sha256sum: command not found
Error: Command failed: bash --noprofile --norc /Users/runner/work/_actions/taiki-e/upload-rust-binary-action/v1/main.sh
```

* [Example workflow](https://github.com/chshersh/tool-sync/actions/runs/3068256999/jobs/4955504990)

The checksum tool is called here:

https://github.com/taiki-e/upload-rust-binary-action/blob/fde83aaa24409a00584de496f2307887610d9286/main.sh#L277

Apparenty, `sha256sum` is not installed on macOS by default:

* https://github.com/actions/runner-images/issues/90

### Workaround for users

Install `coreutils` with `brew` to bring `sha256sum` into the scope:

```yaml
- name: Install coreutils for macOS
  if: matrix.os == 'macOS-latest'
  run: brew install coreutils
```

### Fix in the action

Use the `shasum` tool on macOS with the `-a` option

```shell
shasum -a 256 foo.txt > foo-sha256.txt
```

**Comment by taiki-e** [comment]
Fixed in 1.9.1. Thanks for the report!
