### ISSUE TITLE
5 targets selected but only 3 attachments uploaded

### ISSUE THREAD

**Issue by kris7ian** [taiki-e/upload-rust-binary-action#33]
I'm new to rust and cross-compiling in general. I have the following github action (derived from the examples), it has 5 targets:
https://github.com/kris7ian/aido-cli/blob/main/.github/workflows/release.yaml
The release has only 3 attached binaries though:
https://github.com/kris7ian/aido-cli/releases/tag/v0.5.1
This is the corresponding action:
https://github.com/kris7ian/aido-cli/actions/runs/3285429111
What am I missing?

**Comment by kris7ian** [comment]
Ohh the repository was set to private, I have made it public. Links should work now. Sorry about that.

**Comment by taiki-e** [comment]
Thanks. It seems the problem is that the `target` input option is not passed. 
You need to pass `target: ${{ matrix.target }}` like [readme's cross-compilation example](https://github.com/taiki-e/upload-rust-binary-action#example-workflow-cross-compilation).

**Comment by kris7ian** [comment]
Ahh thank you very much!
