### ISSUE TITLE
Including version number in the file names?

### ISSUE THREAD

**Issue by VorpalBlade** [taiki-e/upload-rust-binary-action#43]
Currently the name format seems to be `<binary-name>-<target-triplet>.<zip/tar.gz>`. For compatibility with [self_update](https://crates.io/crates/self_update) it would be great if it was possible to configure the name to `<binary name>-<version>-<target-triplet>.<zip/tar.gz>`.

See also https://github.com/jaemk/self_update/issues/107. It might be possible to manually make self_update work with the conventions here, but it would be a lot easier if this supported including the version number.

**Comment by taiki-e** [comment]
You can use `archive` input option. See readme for more:
https://github.com/taiki-e/upload-rust-binary-action#example-workflow-customize-archive-name
