### ISSUE TITLE
Retry 500 errors from `gh release`

### ISSUE THREAD

**Issue by Veetaha** [taiki-e/upload-rust-binary-action#52]
See this example release run: [ci link](https://github.com/Veetaha/marker/actions/runs/6132222087/job/16642893066#step:4:266).
Upload failed with the following output.

```
+ gh release upload v0.3.0 cargo-marker-x86_64-unknown-linux-gnu.tar.gz cargo-marker-x86_64-unknown-linux-gnu.zip cargo-marker-x86_64-unknown-linux-gnu.sha256 --clobber
HTTP 502: Server Error (https://api.github.com/repos/Veetaha/marker/releases/assets/125294025)
Error: Process completed with exit code 1.
```

I suggest using exponential backoff to retry the `gh release` operation when it fails.
Here is an example [bash function](https://github.com/rust-marker/marker/blob/4ec73a6893fec46f2460f56ebb203fec4dcf377d/scripts/lib.sh#L11-L62) that we use to retry any network operations.

**Comment by taiki-e** [comment]
Thanks for the report! Fixed in 1.16.1.
