### ISSUE TITLE
Something stopped making builds other than linux

### ISSUE THREAD

**Issue by richardanaya** [taiki-e/upload-rust-binary-action#64]

**Comment by taiki-e** [comment]
Could you tell us specifically what workflow you used and what problems you encountered?

**Comment by richardanaya** [comment]
Hmm, it's strange, my github action 3 weeks ago would do all targets.

Now it seems i'm forced to

```

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    `

**Comment by taiki-e** [comment]
This seems to be fixed by https://github.com/richardanaya/epistemology/commit/5f9ec8a3cf14175c7266d865e06845cae3e9e6f2.
