### ISSUE TITLE
Question: customize the `bin` folder?

### ISSUE THREAD

**Issue by linrongbin16** [taiki-e/upload-rust-binary-action#72]
For example the generated executables binary file is `cargo-ci-template`.

In the final upload assets, the binary is put in the root folder (e.g. `cargo-ci-template-x86_64-unknown-linux-gnu/cargo-ci-template`), is there a way to put it in `bin/cargo-ci-template`?

----------------------------------

Update: when there's some config files we want to package into the `tar.gz`/`zip` tarball, we usually put the executable binary file into `bin` folder.

For example we may want to follow the standards of linux structure when installing a package:

```
./cargo-ci-template-x86_64-unknown-linux-gnu
├── LICENSE.txt
├── README.md
├── bin
│   └── cargo-ci-template
└── share
    ├── icons
    ├── locale
    ├── man
    │   └── man1
    │       └── cargo-ci-template.1
    └── runtime
```

So if we could customize the folder to put the executable file, it will be a big help.

**Comment by taiki-e** [comment]
Yeah, `leading-dir` input option currently only supports `false` (default, no leading dir) and `true` (leading dir same as archive name), but it seems reasonable to support custom leading dir by specifying a string. (I have no strong opinion on whether it should be an extension of an existing option or a new option.)

**Comment by linrongbin16** [comment]
> Yeah, `leading-dir` input option currently only supports `false` (default, no leading dir) and `true` (leading dir same as archive name), but it seems reasonable to support custom leading dir by specifying a string. (I have no strong opinion on whether it should be an extension of an existing option or a new option.)

I think maybe my previous comment confused you.

The `leading-dir` is different from what I'm asked for: the `leading-dir` creates 1 more level of directory (with the `$bin-$target` name).

For example, with `leading-dir=false`, it looks like this:

```
example-x86_64-unknown-linux-gnu

.
├── LICENSE.txt
├── README.md
└── example
```

With `leading-dir=true`, it looks like this:

```
example-x86_64-unknown-linux-gnu

.
├── example-x86_64-unknown-linux-gnu
    ├─ LICENSE.txt
    ├── README.md
    └── example
```

But in my proposal, I want to customize the folder for the `example` executable file, for example put it into a `bin` folder, it looks like this (with `leading-dir=false`):

```
example-x86_64-unknown-linux-gnu

.
├── LICENSE.txt
├── README.md
└── bin
    └── example
```

For example put it into `hello/world` folder, it looks like (with `leading-dir=false`):

```
example-x86_64-unknown-linux-gnu

.
├── LICENSE.txt
├── README.md
└── hello
    └── world
        └── example
```

It actually has nothing to do with the `leading-dir` option.
